server:
  port: 6666
spring:
  datasource:
    url: jdbc:mysql://rm-7xvkbcfxrhi0ht10cto.mysql.rds.aliyuncs.com/backgroundSystem?rewriteBatchedStatements=true&useSSL=false&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8
    username: root
    password: XNXxnx520@
    driverClassName : com.mysql.jdbc.Driver
logging:
  level:
    root: debug

