server:
  port: 8100
  max-http-header-size: 102400
  tomcat:
    max-http-form-post-size: 102400
spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 20MB
  datasource:
    url: ENC(ZSYUag+xsz7GgoYU08vMUH+tHqiYW+H1stPbtVWpyzH+kI4st9pc20BTPtN80W0WMMHe0ODi2yajsf9MNNSwpHipNt7h2VKJ+LpDtX3a2OnQA4bSlT1oHc82jxSuRMSOxtY2ounon3pO9z5kyelAodlqzlAoBONjn4W+z75Basb7l+tJPEQYYC2eoKfb/+iOM2jhN0UV6V0MQAxn69diDGLWK7YLmnP1i+Ab9drzH/VLBLAf7OSl0IWnniKcrAAdhtKJzW1x9bYGOXjrwrAp36cRG0uTSC5YyqsxAp6ljDg=)
    username: ENC(yYyhCiJrQK/rhL69R4y1vqJp2Y7JlTkG)
    password: ENC(8nVpq8EfxZEYu7rSPxjX5pKUFhE56CG8u1x5wgx/QyI=)
    driverClassName: com.mysql.cj.jdbc.Driver

  application:
    name: backgroundSystem

  redis:
    host: localhost
    port: 6379
    password:
    database: 1
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0


logging:
  level:
    sql: debug
    com.background.system*: debug
  file:
#    prod
#    path: /opt/project/log
#    dev
    path: /Users/luozhimin/Desktop/File/daily/backgroundSystem/log

swagger:
  enable: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/*/*.xml

# 加密配置
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

zip:
#  prod
#  path: root/project/upload
#  dev
  path: /Users/luozhimin/Desktop/File/daily/backgroundSystem