server:
  port: 8100
spring:
  datasource:
    url: jdbc:mysql://rm-7xvkbcfxrhi0ht10cto.mysql.rds.aliyuncs.com/backgroundSystem?rewriteBatchedStatements=true&useSSL=false&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: XNXxnx520@
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: backgroundSystem
logging:
  level:
    sql: debug
    com.background.system*: debug

swagger:
  enable: true
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/*/*.xml

