server:
  port: 6666
spring:
  datasource:
    url: jdbc:mysql://rm-7xvkbcfxrhi0ht10cto.mysql.rds.aliyuncs.com/sys?rewriteBatchedStatements=true&useSSL=false&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8
    username: xx
    password: xxx
    driverClassName : com.mysql.jdbc.Driver