server:
  port: 8100
spring:
  servlet:
    multipart:
      max-file-size: 40MB
      max-request-size: 45MB
      location: /Users/sugar/Desktop/BackgroundSystem/upload
  datasource:
    url: ENC(ZSYUag+xsz7GgoYU08vMUH+tHqiYW+H1stPbtVWpyzH+kI4st9pc20BTPtN80W0WMMHe0ODi2yajsf9MNNSwpHipNt7h2VKJ+LpDtX3a2OnQA4bSlT1oHc82jxSuRMSOxtY2ounon3pO9z5kyelAodlqzlAoBONjn4W+z75Basb7l+tJPEQYYC2eoKfb/+iOM2jhN0UV6V0MQAxn69diDGLWK7YLmnP1i+Ab9drzH/VLBLAf7OSl0IWnniKcrAAdhtKJzW1x9bYGOXjrwrAp36cRG0uTSC5YyqsxAp6ljDg=)
    username: ENC(yYyhCiJrQK/rhL69R4y1vqJp2Y7JlTkG)
    password: ENC(8nVpq8EfxZEYu7rSPxjX5pKUFhE56CG8u1x5wgx/QyI=)
    driverClassName: com.mysql.cj.jdbc.Driver

  application:
    name: backgroundSystem

logging:
  level:
    sql: debug
    com.background.system*: debug

swagger:
  enable: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/*/*.xml

# 加密配置
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

# 加入配置vm
#-Djasypt.encryptor.password=xx
zip:
  file: /Users/sugar/Desktop/BackgroundSystem/upload